# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  # Tambah .exe untuk Windows
  cmd = "go build -o ./tmp/main.exe ./cmd/web"
  bin = "./tmp/main.exe"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", "node_modules"]

[log]
  main_only = true

[color]
  main = "cyan"
  watcher = "yellow"
  build = "magenta"
  runner = "green"